.TH L3SYS-QUERY 1 "2024-03-04" "LaTeX3"

.SH NAME
l3sys-query

.SH SYNOPSIS
 Usage l3sys-query<cmd> [<options>] [<spec>]

.SH DESCRIPTION

The l3sys-query script provides a method for TeX runs to obtain system
information via shell escape to Lua. The facilities are more limited than the
similar Java script texosquery, but since it uses Lua, l3sys-query can be
used 'out of the box' with any install TeX system. The script is written taking
account of TeX Live security requirement; it is therefore suitable for use with
restricted shell escape, the standard setting when installing a TeX system.

.SH COMMANDS
Valid targets are:
   ls  Prints a listing based on the <spec> and <options>
   pwd Prints the present working directory

.SH OPTIONS
Valid options are:
   --exclude-dot     Skips over entries starting "." (Unix-hidden)
   --help|-h         Prints this message and exits
   --ignore-case     Ignore case when sorting directory listing
   --recursive|-r    Activates recursive directory listing
   --reverse-sort    Reversing sorting order
   --sort            Method used to sort directory listing
   --type            Selects the type of entry in a directory listing
   --version|-v      Prints version information and exits

.SH "SEE ALSO"
Full manual available via 'texdoc l3sys-query'.

Repository : https://github.com/latex3/l3sys-query

Bug tracker: https://github.com/latex3/l3sys-query/issues

.SH AUTHORS
Copyright (C) 2024 The LaTeX Project
